### ISSUE TITLE
PhoGallery Test

### ISSUE THREAD

**Issue by mo3et** [Mo3et/PhoGallery#1]

**Comment by Mo3et** [comment]
MVC&MVVM

![QQ图片20200525223944](https://user-images.githubusercontent.com/34803812/82822724-d3195a00-9ed8-11ea-944b-66e4d98d4d4b.png)

**Comment by mo3et** [comment]
![image](https://user-images.githubusercontent.com/34803812/115112237-28f66500-9fb7-11eb-92f0-943e35eacdaa.png)

**Comment by mo3et** [comment]
| topic |
| :-- |
| hello|
